In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./images/3_cars.jpg') # bgr

In [3]:
cv2.imshow('orginal_image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img.shape

(795, 1200, 3)

In [5]:
b,g,r = cv2.split(img)

In [6]:
print(b)

[[43 33 36 ... 19 27 39]
 [28 12 11 ...  2  7 20]
 [28 15 16 ...  3 12 25]
 ...
 [60 49 48 ... 27 33 43]
 [58 48 47 ... 27 33 43]
 [75 64 63 ... 44 50 60]]


In [7]:
b.shape,g.shape,r.shape

((795, 1200), (795, 1200), (795, 1200))

In [9]:
cv2.imshow('blue image',b)
cv2.imshow('green image',g)
cv2.imshow('red image',r)
cv2.imshow('original',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Convert Color

In [10]:
img1 = cv2.imread('./images/beach.jpg') # bgr

In [11]:
cv2.imshow('orginal-bgr',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# 1. BGR to gray
gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

# 2. BGR to RGB
img_rgb = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

# 3. BGR to HSV
img_hsv = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)

# 4. BGR to LAB
img_lab = cv2.cvtColor(img1,cv2.COLOR_BGR2LAB)




cv2.imshow('original-bgr',img1)
cv2.imshow('grayscale',gray)
cv2.imshow('rgb',img_rgb)
cv2.imshow('HSV',img_hsv)
cv2.imshow('lab',img_lab)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
gray.shape

(1200, 1500)